[package]
name = "excel2csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.9"
zip = "0.5.10"
quick-xml = "0.30.0"
